compressionLevel: mixed

enableGlobalCache: true

globalFolder: ../.yarn/berry

pnpEnableEsmLoader: true

preferReuse: true

defaultSemverRangePrefix: ''

yarnPath: .yarn/releases/yarn-remote.mjs

packageExtensions:
  '@nestjs/microservices@*':
    peerDependencies:
      '@grpc/proto-loader': '*'
