compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: true

globalFolder: ../.yarn/berry

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  atls:
    npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@nestjs/microservices@*":
    peerDependencies:
      "@grpc/proto-loader": "*"

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.mjs
