compressionLevel: 0

enableGlobalCache: false

pnpEnableEsmLoader: true

preferReuse: true

defaultSemverRangePrefix: ''

yarnPath: .yarn/releases/yarn-remote.cjs

packageExtensions:
  '@nestjs/microservices@*':
    peerDependencies:
      '@grpc/proto-loader': '*'
